Update (Oct 29)

diff --git a/Locator b/Locator
--- a/Locator
+++ b/Locator
@@ -1,37 +1,40 @@
 #!/bin/bash
 
 #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Config
-AutoPick="False"			# Either to use Auto_Pick procedure or not (True/False)
+AutoPick="False"				# Either to use Auto_Pick procedure or not (True/False)
 VM_Name="IRSC_Vel"			# Velocity model name
-initDP="8"				# Initial Depth in km
-CH_St="BH"				# Channel Stream ID
-PnPg_Th="190"				# Distance in km to declare between Pg and Pn
+initDP="10"							# Initial Depth to explor the epicenter (km)
+Depth1="5"							# Upper depth limit to search for the best depth (km)
+Depth2="15"							# Lower depth limit to search for the best depth (km)
+Depth_I="1"							# Depth intervals (km)
+CH_St="BH"							# Channel Stream ID
+PnPg_Th="190"						# Distance in km to declare between Pg and Pn
 Init_Grid_In="1.0"			# Initial Grid Intervals (deg)
-Radius="2.0"				# Search Radius (deg)
-N_Iter="1"				# Number of grid search Iterations over the best 
-					# grid point to maximize the location accuracy.
+Radius="2.0"						# Search Radius (deg)
+N_Iter="1"							# Number of grid search Iterations over the best 
+												# grid point to maximize the location accuracy.							
 												
-LTA_P="30"				# LTA Window Length for P phase Picking
-STA_P="03"				# STA Window Length for P phase Picking
-P_WTh="3"				# STA/LTA Threshold for P phase picking
-Inc="01"				# Sliding Increament, Seconds
-WTh_I="0.5"				# STA/LTA Threshold Increament in Reprocessing
+LTA_P="30"						# LTA Window Length for P phase Picking
+STA_P="03"						# STA Window Length for P phase Picking
+P_WTh="3"							# STA/LTA Threshold for P phase picking
+Inc="01"							# Sliding Increament, Seconds
+WTh_I="0.5"						# STA/LTA Threshold Increament in Reprocessing
 Min_WTh_Th="2.5"			# Minimum acceptable WTh Threshold in Reprocessing
 Method="Class_LR"			# Sliding Method (Class_LR / Class_RR)
 
-#~~~~~~~~~~~~~~ Actual location of EQ (for GMT plot)
+#~~~~~~~~~~~~~~ Actual location of EQ (Only for GMT plot)
 EVELAT="34.56"
 EVELON="47.68"
 
 ##### SAC Config
-F1_P=0.8				# Band-Pass Filter lower corner
-F2_P=5.0				# Band-Pass Filter upper corner
+F1_P=0.8							# Band-Pass Filter lower corner
+F2_P=5.0							# Band-Pass Filter upper corner
 
 
 #  Class_RR:	<=====================> LTA
-#				<=====> STA	
+#															<=====> STA	
 #  Class_LR:	<=====================> LTA
-#				    <=====> STA
+#				  												<=====> STA
 
 #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ bODY sCript (Do not ChAnge)
 
@@ -202,12 +205,14 @@ map ()
 	gmt psxy -R -J All_Grds.dat -Sc0.055c -Gblack -i1,0 -K -O >> Map.ps
 	echo "$EVELON $EVELAT" | gmt psxy -R -J -Sa0.25 -Gred -i0,1 -K -O >> Map.ps
 	gmt psxy -R -J stations.used -St0.25c -Gblack -i2,1 -K -O >> Map.ps
-	cat Epicenter.dat | gmt psxy -R -J -Sc0.25 -Gred -i1,0 -K -O >> Map.ps
+	cat Epicenter.dat | head -1 | gmt psxy -R -J -Sc0.25 -Gred -i1,0 -K -O >> Map.ps
+	clear && echo -e "\nFinal Earthquake Location:\n"	
+	cat $input/Epicenter.dat	
 }
 
 Regression ()
 {
-	awk '{print $3,$4}' $1 | gmt regress -Eo -Fp -o5
+	awk '{print $4,$3}' $1 | gmt regress -Eo -Fp -o5
 }
 
 vel_Reader ()
@@ -309,7 +314,6 @@ Grid_Search ()
 
 }
 
-
 TT_Calculator ()
 {
 	cat $input/P_Arrivals.dat | while read info; do
@@ -342,6 +346,48 @@ TT_Calculator ()
 	done	
 }
 
+Depth_BT ()
+{
+	evela=`cut -f 1 -d " " Epicenter.dat`
+	evelo=`cut -f 2 -d " " Epicenter.dat`
+	echo "Let's Probe the Depth ... "
+	for Dep in $(seq "$Depth1" "$Depth_I" "$Depth2"); do
+		echo "Assessing Depth $Dep posibility ..."
+		sed -i "/source_depth =/c\source_depth = $Dep * km" $ttime		
+		cat stations.used | while read Sinfo; do
+			stnam=`echo $Sinfo | awk '{print $1}'`
+			stlat=`echo $Sinfo | awk '{print $2}'` 
+			stlon=`echo $Sinfo | awk '{print $3}'` 				
+			dist=`distance $stlat $stlon $evela $evelo` 
+			(( `echo "$dist < $PnPg_Th" | bc -l` )) && phase="p" || phase="P"
+			sed -i "/distances = /c\distances = num.linspace($dist,$dist,1)*km * cake.m2d" $ttime 
+			sed -i "/Phase =/c\Phase = cake.PhaseDef(\'$phase\')" $ttime
+			TT=`python $ttime 2> /dev/null` && TTm=`echo $TT | awk '{print $2}'`
+			[[ -z "$TTm" ]] && continue
+			echo "$stnam $TTm" 
+		done > traveltimes.dat	
+		[[ ! -s traveltimes.dat ]] && echo "No synthetic travel-time calculated for Depth = $Dep" && continue
+
+		closest_st_ttime=`grep -w "$Closest_Sta" traveltimes.dat | cut -f 2 -d " "`
+		[[ -z "$closest_st_ttime" ]] && echo "Program failed to calculate synthetic T-time for the nearest station!" && exit 1
+		
+		cat traveltimes.dat | while read info; do
+			stname=`echo $info | awk '{print $1}'`
+			[[ "$stname" = "$Closest_Sta" ]] && continue
+			sttime=`echo $info | awk '{print $2}'`
+			diff=`echo "$sttime - $closest_st_ttime" | bc -l`
+			dist=`grep -w "$stname" $input/dist_time.dat | cut -f 3 -d " "`
+			echo "$stnme $stname $dist $diff"
+		done > synt_tdiffs.dat	
+			
+		Syn_Slope=`Regression synt_tdiffs.dat`
+		Slope_Diff=`echo "scale=5; $Syn_Slope - $Real_Slope" | bc -l` && Slope_Diff=`Absolute $Slope_Diff`
+		echo "$Dep $Slope_Diff" >> Dep_RMS.dat
+	done	
+	echo Depth `sort -n -k 2 $input/Dep_RMS.dat 2> /dev/null | cut -f 1 -d " " | head -1` >> $input/Epicenter.dat	
+
+}
+
 Cleaner
 if [[ "$AutoPick" = "True" ]] || [[ "$AutoPick" = "true" ]]; then
 	P_Picker
@@ -360,4 +406,5 @@ fi
 vel_Reader
 Real_Regression
 TT_Calculator
+Depth_BT
 map
